%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-gazebo-video-monitor-plugins
Version:        0.7.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS gazebo_video_monitor_plugins package

License:        GPLv3
Source0:        %{name}-%{version}.tar.gz

Requires:       opencv-devel
Requires:       ros-noetic-gazebo-ros
Requires:       ros-noetic-gazebo-video-monitor-msgs
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-std-srvs
BuildRequires:  opencv-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-gazebo-ros
BuildRequires:  ros-noetic-gazebo-video-monitor-msgs
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-std-srvs
BuildRequires:  yaml-cpp-devel
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
gazebo_video_monitor_plugins is a package that lets the user record videos of a
Gazebo simulation. It provides a multicamera sensor that can be used for
creating different types of videos with multiple views from inside the gazebo
world. There is a number of plugins already available in the package, but more
can be developed by the user, with minimal effort, to fit arbitrary use cases.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Mon Aug 23 2021 Nick Lamprianidis <nlamprian@gmail.com> - 0.7.0-1
- Autogenerated by Bloom

* Tue Dec 15 2020 Nick Lamprianidis <nlamprian@gmail.com> - 0.6.0-1
- Autogenerated by Bloom

